version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: edu_db
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: edu_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build: .
    command: gunicorn edu_platform.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=edu_db
      - DATABASE_USER=edu_user
      - DATABASE_PASSWORD=edu_pass
      - DATABASE_HOST=db
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data:
