# Generated by Django 5.2 on 2025-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='course',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='title',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
